import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

import '@/app/css/bootstrap.min.css';
import '@/app/css/aos.css';
import '@/app/css/tooplate-gymso-style.css';

import Script from 'next/script'
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app'
}

export default function RootLayout({
	children
}: {
	children: React.ReactNode
}) {
	return (
		<html lang="en">
			<head>
				<meta http-equiv="X-UA-Compatible" content="IE=Edge" />
				<meta name="description" content="" />
				<meta name="keywords" content="" />
				<meta name="author" content="" />
				<meta
					name="viewport"
					content="width=device-width, initial-scale=1, maximum-scale=1"
				/>
				{/* <!-- MAIN CSS --> */}

				<Script src="/event-gen/js/jquery.min.js"></Script>
				<Script src="/event-gen/js/bootstrap.min.js"></Script>
				<Script src="/event-gen/js/aos.js"></Script>
				<Script src="/event-gen/js/smoothscroll.js"></Script>
				<Script src="/event-gen/js/custom.js"></Script>

			</head>
			<body className={inter.className}>{children}</body>
		</html>
	)
}
