import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app'
}

export default function RootLayout({
	children
}: {
	children: React.ReactNode
}) {
	return (
		<html lang="en">
			<head>
				<meta http-equiv="X-UA-Compatible" content="IE=Edge" />
				<meta name="description" content="" />
				<meta name="keywords" content="" />
				<meta name="author" content="" />
				<meta
					name="viewport"
					content="width=device-width, initial-scale=1, maximum-scale=1"
				/>

				<link rel="stylesheet" href="/css/bootstrap.min.css" />
				<link rel="stylesheet" href="/css/font-awesome.min.css" />
				<link rel="stylesheet" href="/css/aos.css" />

				{/* <!-- MAIN CSS --> */}
				<link rel="stylesheet" href="/css/tooplate-gymso-style.css" />
				<script src="/js/jquery.min.js"></script>
				<script src="/js/bootstrap.min.js"></script>
				<script src="/js/aos.js"></script>
				<script src="/js/smoothscroll.js"></script>
				<script src="/js/custom.js"></script>
			</head>
			<body className={inter.className}>{children}</body>
		</html>
	)
}
